### ISSUE TITLE
YAML module missing after pipenv install

### ISSUE THREAD

**Issue by selpan** [2ndWatch/cloudendure-python#94]
Using pipenv to install the packages for `cloudendure-python` and trying to run the CLI commands throws an error for a missing module.

```bash
nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master
$ pipenv install
Creating a virtualenv for this project…
Pipfile: /Users/nselpa/gitrepos/cloudendure-python/Pipfile
Using /usr/local/bin/python3 (3.7.6) to create virtualenv…
⠇ Creating virtual environment...Already using interpreter /usr/local/opt/python/bin/python3.7
Using base prefix '/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/bin/python3.7
Also creating executable in /Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/local/bin/python3

✔ Successfully created virtual environment! 
Virtualenv location: /Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7
Installing dependencies from Pipfile.lock (bb2ed3)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 25/25 — 00:01:02

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master
$ pipenv run ce
Traceback (most recent call last):
  File "/Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/bin/ce", line 11, in <module>
    load_entry_point('cloudendure', 'console_scripts', 'ce')()
  File "/Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/Users/nselpa/.local/share/virtualenvs/cloudendure-python-4DQesPY7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/nselpa/gitrepos/cloudendure-python/cloudendure/cloudendure.py", line 18, in <module>
    from .api import CloudEndureAPI
  File "/Users/nselpa/gitrepos/cloudendure-python/cloudendure/api.py", line 24, in <module>
    from cloudendure.config import CloudEndureConfig
  File "/Users/nselpa/gitrepos/cloudendure-python/cloudendure/config.py", line 10, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master
$ 
```

Adding `pyyaml` to the Pipfile's `[packages]` section results in a successful run:

```bash
nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master
$ vi Pipfile

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master [!]
$ pipenv install
Pipfile.lock (f49ee6) out of date, updating to (bb2ed3)…
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (f49ee6)!
Installing dependencies from Pipfile.lock (f49ee6)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 26/26 — 00:00:41

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master [!]
$ cloudendure
bash: cloudendure: command not found

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master [!]
$ pipenv run cloudendure
You must configure your authentication credentials!
Failed to authenticate with CloudEndure! Please check your credentials and try again!

nselpa at pa-ps-mac-0508 in ~/gitrepos/cloudendure-python on master [!]
$ 
```
A PR with the updated `Pipfile` and `Pipfile.lock` files to address the issue will be provided.

**Comment by mbeacom** [comment]
This issue was resolving in #95
